import json
import os
import tempfile

from .config import PRODUCTS
from .ledger import load_ledger, load_product_metadata
from .parser import scan_valuations


HTML = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>创新金融业务总部fof收益计算</title><style>
:root{--bg:#f4f1ea;--ink:#18201d;--muted:#68736d;--card:#fffdf8;--line:#d9ddd5;--green:#0f6b50;--red:#b34432;--gold:#c6923c}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.55 system-ui,"Microsoft YaHei",sans-serif}.wrap{max-width:1460px;margin:auto;padding:28px}h1{font:600 31px/1.2 Georgia,"Microsoft YaHei";margin:0}.sub,.label{color:var(--muted)}.toolbar{display:flex;align-items:end;gap:12px;flex-wrap:wrap;margin:20px 0}.field{display:flex;flex-direction:column;gap:5px}.field label,th{font-size:12px;color:var(--muted)}input{padding:9px 11px;border:1px solid var(--line);border-radius:8px;background:white}button{border:0;border-radius:8px;padding:10px 18px;background:var(--green);color:#fff;cursor:pointer}.summary{margin-bottom:12px;overflow:auto}.summary table{margin:0;min-width:900px}.summary th,.summary td{padding:12px}.summary tbody tr:last-child td{border-bottom:0}.summary td:not(:first-child){font-size:17px;font-weight:650;white-space:nowrap}.card,.panel{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:17px}.value{font-size:22px;font-weight:650;margin-top:4px}.positive{color:var(--red)}.negative{color:var(--green)}.layout{display:grid;grid-template-columns:390px 1fr;gap:16px}.row{display:flex;justify-content:space-between;gap:12px}.list{display:flex;flex-direction:column;gap:8px;max-height:72vh;overflow:auto;margin-top:10px}.item{padding:12px;border:1px solid var(--line);border-radius:9px;cursor:pointer;background:#fff}.item.active{border-color:var(--green);box-shadow:0 0 0 1px var(--green)}.item small{color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.metric{background:#f7f5ef;border-radius:9px;padding:12px}.warn{background:#fff2d9;border-left:3px solid var(--gold);padding:9px 12px;margin:8px 0}.ok{background:#e9f4ee;border-left:3px solid var(--green);padding:9px 12px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}canvas{width:100%;height:270px;border:1px solid var(--line);border-radius:8px;cursor:crosshair}.chart-tip{position:fixed;z-index:1000;display:none;pointer-events:none;background:#18201d;color:#fff;padding:8px 10px;border-radius:7px;box-shadow:0 4px 14px #0003;font-size:12px;line-height:1.6;white-space:nowrap}.check{width:17px;height:17px}.muted-row{opacity:.5}@media(max-width:850px){.wrap{padding:14px}.layout{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}}
</style></head><body><div class="wrap"><h1>创新金融业务总部fof收益计算</h1><div class="sub">非交易日估值边界向前取最近估值表；交易日须有当日估值表才计入“已计算产品”；申购赎回金额全部采用《专户资金台账》确认数据</div><div class="toolbar"><div class="field"><label>开始日期</label><input id="startDate" type="date"></div><div class="field"><label>结束日期</label><input id="endDate" type="date"></div><button onclick="calculate()">计算</button><span id="rangeHint" class="sub"></span></div><div id="summary" class="summary panel"></div><div class="panel" style="margin-bottom:16px"><b>汇总计算口径</b><div class="sub" style="margin-top:8px;display:grid;gap:6px"><div>所有产品期末资产：组内每只顶层产品在结束日期前最近估值的资产净值之和，仅由结束日期决定。</div><div>区间收益：仅汇总组内数据完整且可计算产品，公式为期末资产－期初资产－申购＋赎回＋现金分红。</div><div>已计算产品：开始日期和结束日期均有估值表的产品数量／该组顶层产品数量；若所选日期为非交易日，允许向前取最近估值表。</div><div>当前总投资额：组内产品在《专户资金台账》余额表中的本金之和。</div><div>创新金融业务总部所有组保持全部顶层产品口径。</div><div>自营-证投组不含中金财富私享1554号及盛乾同行5号，并从天玑13号中穿透扣除砚博指增6号：期末资产扣除所选结束日前最近披露市值，区间收益扣除按相邻估值表可归属的砚博期间收益，当前总投资额扣除砚博最新披露成本；底层期间收益为估算口径。</div><div>FOF1组包含除盛乾同行5号、五矿证券FOF50号、FOF51号以外的所有顶层产品。</div><div>FOF2研究所组包含盛乾同行5号、五矿证券FOF50号、FOF51号。</div><div>五矿证券FOF50号、FOF51号不在当前15只产品白名单中，暂无估值及台账数据，暂不计入金额和产品数量。</div></div></div><div class="layout"><div class="panel"><b>产品列表</b><div id="list" class="list"></div><div class="sub" style="margin-top:12px">底层产品（穿透列示）</div><div id="yanboStandalone"></div></div><div id="detail" class="panel"></div></div></div>
<script>const RAW=__DATA__,DAY=86400000;const money=v=>v==null?'—':new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(v);const pct=v=>v==null?'无法计算':v.toFixed(2)+'%';const cls=v=>v>0?'positive':v<0?'negative':'';let report=[],active=0;
const YANBO='砚博指增6号私募证券投资基金',TIANJI='第一创业天玑13号单一资产管理计划',SHENGQIAN5='国金资管盛乾同行5号FOF单一资产管理计划',ZHONGJIN1554='中金财富私享1554号FOF单一资产管理计划',GROUPS=[{name:'创新金融业务总部所有组（所有产品）',test:p=>true},{name:'自营-证投组',test:p=>![ZHONGJIN1554,SHENGQIAN5].includes(p.name),exclude_holding:YANBO},{name:'FOF1组',test:p=>p.name!==SHENGQIAN5},{name:'FOF2研究所组',test:p=>p.name===SHENGQIAN5}];
function ds(a,b){return Math.round((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/DAY)}function shift(d,n){const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}function before(a,d){return a.filter(x=>x.valuation_date<=d).slice(-1)[0]||null}function nonTradingDate(d){return !RAW.products.some(p=>p.points.some(x=>x.valuation_date===d))}function boundaryComplete(point,requested){return !!point&&(point.valuation_date===requested||nonTradingDate(requested))}
function xnpv(rate,flows){if(rate<=-1)return Infinity;const d0=flows[0].date;return flows.reduce((s,f)=>s+f.value/Math.pow(1+rate,ds(d0,f.date)/365),0)}function xirr(flows){if(!flows.some(x=>x.value<0)||!flows.some(x=>x.value>0))return null;const grid=[-.9999,-.99,-.9,-.5,0,.05,.1,.2,.5,1,2,5,10,100,1000,1000000];for(let i=1;i<grid.length;i++){let lo=grid[i-1],hi=grid[i],a=xnpv(lo,flows),b=xnpv(hi,flows);if(!isFinite(a)||!isFinite(b)||a*b>0)continue;for(let j=0;j<150;j++){const mid=(lo+hi)/2,m=xnpv(mid,flows);if(Math.abs(m)<.01)return mid;if(a*m<=0){hi=mid;b=m}else{lo=mid;a=m}}return(lo+hi)/2}return null}
function holdingReport(points,inception){const series=inception?[{holdings:[]}].concat(points):points,all=new Map;for(let i=1;i<series.length;i++){const pm=new Map((series[i-1].holdings||[]).map(h=>[h.code,h])),cm=new Map((series[i].holdings||[]).map(h=>[h.code,h])),keys=new Set([...pm.keys(),...cm.keys()]);keys.forEach(code=>{const a=pm.get(code),b=cm.get(code),r=all.get(code)||{code,name:(b||a).name,period_profit:0,uncertain:false,status:new Set};if(a&&b){const basis=Math.min(a.quantity,b.quantity);r.period_profit+=basis*(b.price-a.price);r.status.add(Math.abs(a.quantity-b.quantity)>Math.max(a.quantity*.0001,1)?'持仓变化，按可比份额估算':'持仓不变')}else if(b){r.period_profit+=b.valuation_gain==null&&b.cost!=null?b.market_value-b.cost:(b.valuation_gain||0);r.status.add('区间新增，按当前浮盈亏')}else{r.uncertain=true;r.status.add('区间退出，退出收益未归属')}if(b)r.ending=b;all.set(code,r)})}return[...all.values()].map(r=>({code:r.code,name:r.name,period_profit:r.period_profit,current_gain:r.ending?r.ending.valuation_gain:null,market_value:r.ending?r.ending.market_value:0,quantity:r.ending?r.ending.quantity:0,status:[...r.status].join('；'),uncertain:r.uncertain})).sort((a,b)=>Math.abs(b.period_profit)-Math.abs(a.period_profit))}
function result(p,start,end){const prior=before(p.points,start),last=before(p.points,end),dated=p.flows.filter(f=>f.flow_date).sort((a,b)=>a.flow_date.localeCompare(b.flow_date)),firstInvestment=dated.find(f=>f.amount>0),ledgerNet=dated.reduce((s,f)=>s+f.amount,0),tolerance=Math.max(1,Math.abs(p.total_investment||0)*.000001),ledgerReconciled=p.total_investment!=null&&Math.abs(ledgerNet-p.total_investment)<=tolerance,inception=!prior;if(!last)return{name:p.name,status:'insufficient',message:'结束日期之前没有估值表'};if(prior&&last.valuation_date<=prior.valuation_date)return{name:p.name,status:'insufficient',message:'区间内不足两个不同估值日'};if(!ledgerReconciled)return{name:p.name,status:'insufficient',message:'台账累计净投资与当前总投资额不一致，历史建仓/追加/赎回流水不完整，暂不计算收益'};if(inception&&!firstInvestment)return{name:p.name,status:'insufficient',message:'开始日期前无估值表，且台账未找到首次建仓流水'};if(inception&&firstInvestment.flow_date<start)return{name:p.name,status:'insufficient',message:'台账显示所选开始日前已建仓，但缺少期初估值表，暂不计算收益'};if(inception&&firstInvestment.flow_date>last.valuation_date)return{name:p.name,status:'insufficient',message:'结束日期前没有可与估值表对应的建仓流水'};const first=prior||{valuation_date:firstInvestment.flow_date,net_assets:0},points=p.points.filter(x=>x.valuation_date>=first.valuation_date&&x.valuation_date<=last.valuation_date);if(inception&&!points.length)return{name:p.name,status:'insufficient',message:'首次建仓后没有估值表'};const dividends=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],gap=(b.accumulated_nav-b.nav)-(a.accumulated_nav-a.nav);if(gap>Math.max(b.nav*.0001,.0001))dividends.push({date:b.valuation_date,per_share:gap,amount:gap*a.shares,status:'估值表推定，待公告或流水确认'})}
const included=dated.filter(f=>(inception?f.flow_date>=first.valuation_date:f.flow_date>first.valuation_date)&&f.flow_date<=last.valuation_date),net=included.reduce((s,x)=>s+x.amount,0),subscriptions=included.filter(x=>x.amount>0).reduce((s,x)=>s+x.amount,0),redemptions=-included.filter(x=>x.amount<0).reduce((s,x)=>s+x.amount,0),dividendAmount=dividends.reduce((s,x)=>s+x.amount,0),profit=last.net_assets-first.net_assets-net+dividendAmount,xf=[{date:first.valuation_date,value:-first.net_assets},...included.map(x=>({date:x.flow_date,value:-x.amount})),...dividends.map(x=>({date:x.date,value:x.amount})),{date:last.valuation_date,value:last.net_assets}],annual=xirr(xf),complete=boundaryComplete(prior,start)&&boundaryComplete(last,end);return{name:p.name,status:'ok',boundary_complete:complete,first,last,points,flows:included,dividends,dividendAmount,net,subscriptions,redemptions,profit,annualized:annual==null?null:annual*100,days:ds(first.valuation_date,last.valuation_date),inception,holdings:holdingReport(points,inception),requested_start:start,requested_end:end,total_investment:p.total_investment,approved_quota:p.approved_quota}}
function calculate(){const start=startDate.value,end=endDate.value;if(!start||!end||start>=end){alert('请选择有效日期区间');return}report=RAW.products.map(p=>result(p,start,end));const owner=RAW.products.find(p=>p.name===TIANJI),ownerReport=report.find(p=>p.name===TIANJI&&p.status==='ok'),endPoint=owner&&before(owner.points,end),endHolding=endPoint&&(endPoint.holdings||[]).find(h=>h.name===YANBO),latestPoint=owner&&owner.points.slice(-1)[0],latestHolding=latestPoint&&(latestPoint.holdings||[]).find(h=>h.name===YANBO),periodHolding=ownerReport&&(ownerReport.holdings||[]).find(h=>h.name===YANBO),series=ownerReport?(ownerReport.points||[]).map(p=>{const h=(p.holdings||[]).find(x=>x.name===YANBO);return h?{valuation_date:p.valuation_date,nav:h.price,accumulated_nav:h.price,net_assets:h.market_value,cost:h.cost,valuation_gain:h.valuation_gain}:null}).filter(Boolean):[];window.yanboView=endHolding?{end_date:endPoint.valuation_date,holding:endHolding,latest:latestHolding,period_profit:periodHolding?periodHolding.period_profit:null,series}:null;const rows=GROUPS.map(g=>{const products=RAW.products.filter(g.test),names=new Set(products.map(p=>p.name)),valid=report.filter(x=>x.status==='ok'&&names.has(x.name)),complete=valid.filter(x=>x.boundary_complete);let ending=products.map(p=>before(p.points,end)).filter(Boolean).reduce((s,p)=>s+p.net_assets,0),profit=valid.reduce((s,p)=>s+p.profit,0),investment=products.reduce((s,p)=>s+(p.total_investment||0),0);if(g.exclude_holding){ending-=endHolding?endHolding.market_value||0:0;profit-=periodHolding?periodHolding.period_profit||0:0;investment-=latestHolding?latestHolding.cost||0:0}return{name:g.name,ending,profit,calculated:complete.length,total:products.length,investment}});summary.innerHTML=`<table><thead><tr><th>分组</th><th>所有产品期末资产</th><th>区间收益</th><th>已计算产品</th><th>所有产品当前总投资额</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.name}</b></td><td>${money(r.ending)}</td><td class=${cls(r.profit)}>${money(r.profit)}</td><td>${r.calculated} / ${r.total}</td><td>${money(r.investment)}</td></tr>`).join('')}</tbody></table>`;rangeHint.textContent=RAW.ledger_errors.length?'台账存在 '+RAW.ledger_errors.length+' 项解析提示':'';list.innerHTML=report.map((p,i)=>`<div class=item id=p${i} onclick="show(${i})"><div>${p.name}</div><div class=row><small>${p.status==='ok'?p.first.valuation_date+' → '+p.last.valuation_date:p.message}</small><b class=${cls(p.profit)}>${p.status==='ok'?money(p.profit):''}</b></div></div>`).join('');yanboStandalone.innerHTML=window.yanboView?`<div class=item id=yanboItem onclick="showYanbo()"><div>${YANBO}</div><div class=row><small>天玑13号底层持仓 · 至 ${window.yanboView.end_date}</small><b class=${cls(window.yanboView.period_profit)}>${money(window.yanboView.period_profit)}</b></div></div>`:`<div class="item muted-row"><div>${YANBO}</div><small>所选结束日前没有可用持仓数据</small></div>`;show(Math.min(active,report.length-1))}
function show(i){active=i;document.querySelectorAll('.item').forEach(x=>x.classList.remove('active'));document.getElementById('p'+i).classList.add('active');const p=report[i];if(p.status!=='ok'){detail.innerHTML=`<h2>${p.name}</h2><div class=warn>${p.message}</div>`;return}const boundaryWarn=p.inception?'<div class=ok>台账确认该产品在所选区间内首次建仓：期初资产按0处理，并从首次建仓日起计入全部追加和赎回。</div>':p.first.valuation_date!==p.requested_start||p.last.valuation_date!==p.requested_end?'<div class=warn>所选日期无估值表，已向前选取最近估值表。若申赎发生在边界附近，请核对台账日期与估值确认日期是否一致。</div>':'';detail.innerHTML=`<h2 style="margin:0">${p.name}</h2><div class=sub>计算区间 ${p.first.valuation_date} 至 ${p.last.valuation_date}（${p.days}天）</div>${boundaryWarn}<div class=metrics>${[['当前总投资额',money(p.total_investment),''],['2026年会议批准额度',money(p.approved_quota),''],['期末资产',money(p.last.net_assets),''],['区间收益',money(p.profit),cls(p.profit)],['XIRR年化收益率',pct(p.annualized),cls(p.annualized)],['现金分红',money(p.dividendAmount),''],['台账申购',money(p.subscriptions),''],['台账赎回',money(p.redemptions),''],['台账净现金流',money(p.net),'']].map(x=>`<div class=metric><div class=label>${x[0]}</div><div class="value ${x[2]}">${x[1]}</div></div>`).join('')}</div><canvas id=chart width=960 height=270></canvas><h3>底层投资期间收益</h3>${holdingTable(p)}<h3>台账现金流</h3>${flowTable(p)}<h3>分红</h3>${dividendTable(p)}<h3>估值明细</h3><table><thead><tr><th>估值日</th><th>单位净值</th><th>累计净值</th><th>总份额（仅核验）</th><th>资产净值</th></tr></thead><tbody>${p.points.map(x=>`<tr><td>${x.valuation_date}</td><td>${x.nav}</td><td>${x.accumulated_nav}</td><td>${x.shares.toLocaleString()}</td><td>${money(x.net_assets)}</td></tr>`).join('')}</tbody></table>`;draw(p.points)}
function showYanbo(){const y=window.yanboView;if(!y)return;document.querySelectorAll('.item').forEach(x=>x.classList.remove('active'));document.getElementById('yanboItem').classList.add('active');const h=y.holding,currentGain=h.valuation_gain==null&&h.cost!=null?h.market_value-h.cost:h.valuation_gain;detail.innerHTML=`<h2 style="margin:0">${YANBO}</h2><div class=sub>天玑13号底层持仓 · 期末估值日 ${y.end_date}</div><div class=warn>期间收益按天玑13号相邻估值表中的持仓数量和价格变化归属，为底层估算口径；不含无法归属的退出损益、现金及费用。</div><div class=metrics>${[['期末市值',money(h.market_value),''],['期末成本',money(h.cost),''],['累计浮盈亏',money(currentGain),cls(currentGain)],['所选区间估算收益',money(y.period_profit),cls(y.period_profit)],['持有份额',h.quantity==null?'—':h.quantity.toLocaleString(),''],['期末价格',h.price==null?'—':h.price.toFixed(4),'']].map(x=>`<div class=metric><div class=label>${x[0]}</div><div class="value ${x[2]}">${x[1]}</div></div>`).join('')}</div><canvas id=chart width=960 height=270></canvas><h3>持仓估值明细</h3><table><thead><tr><th>估值日</th><th>价格</th><th>市值</th><th>成本</th><th>浮盈亏</th></tr></thead><tbody>${y.series.map(p=>`<tr><td>${p.valuation_date}</td><td>${p.nav}</td><td>${money(p.net_assets)}</td><td>${money(p.cost)}</td><td class=${cls(p.valuation_gain)}>${money(p.valuation_gain)}</td></tr>`).join('')}</tbody></table>`;draw(y.series)}
function holdingTable(p){if(!p.holdings.length)return'<div class=sub>该产品估值文件未披露可解析的底层持仓明细。</div>';const estimated=p.holdings.reduce((s,h)=>s+h.period_profit,0),uncertain=p.holdings.filter(h=>h.uncertain).length;return`<div class="${uncertain?'warn':'ok'}">底层可归属期间估算收益 ${money(estimated)}。${uncertain?'有 '+uncertain+' 项区间退出持仓缺少成交价，退出收益未归属；':''}该数值不含现金、费用及无法归属的已实现损益，不要求与FOF区间总收益完全一致。</div><table><thead><tr><th>底层产品</th><th>期末市值</th><th>当前浮盈亏</th><th>期间估算收益</th><th>说明</th></tr></thead><tbody>${p.holdings.map(h=>`<tr><td>${h.name}<div class=sub>${h.code}</div></td><td>${money(h.market_value)}</td><td class=${cls(h.current_gain)}>${money(h.current_gain)}</td><td class=${cls(h.period_profit)}>${money(h.period_profit)}</td><td>${h.status}</td></tr>`).join('')}</tbody></table>`}
function flowTable(p){if(!p.flows.length)return'<div class=sub>该估值区间内没有台账现金流。</div>';return`<table><thead><tr><th>日期</th><th>类型</th><th>金额</th><th>来源</th></tr></thead><tbody>${p.flows.map(f=>`<tr><td>${f.flow_date}</td><td>${f.amount>=0?'申购':'赎回'}</td><td>${money(Math.abs(f.amount))}</td><td>${f.source_year}年第${f.source_row}行</td></tr>`).join('')}</tbody></table>`}
function dividendTable(p){if(!p.dividends.length)return'<div class=sub>累计净值与单位净值未显示现金分红迹象。</div>';return`<table><thead><tr><th>推定日期</th><th>每份分红</th><th>推定分红金额</th><th>状态</th></tr></thead><tbody>${p.dividends.map(d=>`<tr><td>${d.date}</td><td>${d.per_share.toFixed(6)}</td><td>${money(d.amount)}</td><td>${d.status}</td></tr>`).join('')}</tbody></table>`}
function draw(points){const c=document.getElementById('chart'),x=c.getContext('2d'),L=70,R=18,T=18,B=55,vals=points.map(p=>p.accumulated_nav),min=Math.min(...vals),max=Math.max(...vals),span=max-min||.01,w=c.width-L-R,h=c.height-T-B;x.clearRect(0,0,c.width,c.height);x.font='12px Microsoft YaHei';x.strokeStyle='#d9ddd5';x.fillStyle='#68736d';for(let i=0;i<=4;i++){const y=T+h*i/4,v=max-span*i/4;x.beginPath();x.moveTo(L,y);x.lineTo(L+w,y);x.stroke();x.fillText(v.toFixed(4),8,y+4)}x.save();x.translate(16,T+h/2);x.rotate(-Math.PI/2);x.fillText('累计净值',-25,0);x.restore();x.strokeStyle='#0f6b50';x.lineWidth=3;x.beginPath();points.forEach((p,i)=>{const px=L+i*w/Math.max(points.length-1,1),py=T+(max-p.accumulated_nav)*h/span;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();const labels=[0,Math.floor((points.length-1)/2),points.length-1].filter((v,i,a)=>a.indexOf(v)===i);x.fillStyle='#68736d';labels.forEach(i=>{const px=L+i*w/Math.max(points.length-1,1);x.fillText(points[i].valuation_date,Math.max(L,Math.min(px-32,c.width-78)),c.height-28)});x.fillText('日期',L+w/2-12,c.height-7);let tip=document.getElementById('chartTip');if(!tip){tip=document.createElement('div');tip.id='chartTip';tip.className='chart-tip';document.body.appendChild(tip)}c.onmousemove=e=>{const rect=c.getBoundingClientRect(),cx=(e.clientX-rect.left)*c.width/rect.width,index=Math.max(0,Math.min(points.length-1,Math.round((cx-L)/Math.max(w,1)*Math.max(points.length-1,1)))),p=points[index];tip.innerHTML=`<b>${p.valuation_date}</b><br>单位净值：${p.nav}<br>累计净值：${p.accumulated_nav}<br>资产净值：${money(p.net_assets)}`;tip.style.display='block';tip.style.left=Math.min(e.clientX+14,window.innerWidth-tip.offsetWidth-8)+'px';tip.style.top=Math.min(e.clientY+14,window.innerHeight-tip.offsetHeight-8)+'px'};c.onmouseleave=()=>tip.style.display='none'}
startDate.value=RAW.default_start;endDate.value=RAW.default_end;calculate();</script></body></html>'''


def build_index(products_dir="products", output="index.html", year=None, month=None):
    snapshots, parse_errors = scan_valuations(products_dir)
    ledger_path = os.path.join(os.path.dirname(os.path.abspath(products_dir)), "专户资金台账.xlsx")
    flows, ledger_errors = load_ledger(ledger_path, snapshots) if os.path.exists(ledger_path) else ([], [{"error": "未找到专户资金台账.xlsx"}])
    metadata, metadata_errors = load_product_metadata(ledger_path) if os.path.exists(ledger_path) else ({}, [])
    ledger_errors.extend(metadata_errors)
    grouped = {name: {"name": name, "points": [], "flows": [],
                      "total_investment": metadata.get(name, {}).get("total_investment"),
                      "approved_quota": metadata.get(name, {}).get("approved_quota", 0)} for name in PRODUCTS}
    for snapshot in snapshots:
        grouped[snapshot.product]["points"].append(snapshot.as_dict())
    for flow in flows:
        grouped[flow.product]["flows"].append(flow.as_dict())
    dates = []
    for product in grouped.values():
        product["points"].sort(key=lambda item: item["valuation_date"])
        product["flows"].sort(key=lambda item: (item["flow_date"] or "9999", item["flow_id"]))
        dates.extend(item["valuation_date"] for item in product["points"])
    payload = {"products": list(grouped.values()), "parse_errors": parse_errors, "ledger_errors": ledger_errors,
               "default_start": "2026-06-30" if "2026-06-30" in dates else min(dates), "default_end": max(dates)}
    output = os.path.abspath(output)
    output_dir = os.path.dirname(output)
    os.makedirs(output_dir, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=output_dir,
                                         prefix=".index-", suffix=".tmp", delete=False) as handle:
            temporary = handle.name
            handle.write(HTML.replace("__DATA__", json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")))
        os.replace(temporary, output)
    finally:
        if temporary and os.path.exists(temporary):
            os.remove(temporary)
    return output, {"summary": {"analyzable_products": sum(len(p["points"]) >= 2 for p in grouped.values())},
                    "ledger_flows": len(flows), "ledger_errors": ledger_errors}
